# Generated by Django 3.1.13 on 2021-12-02 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20211202_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('max_size', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('start_location', models.CharField(max_length=25)),
                ('end_location', models.CharField(max_length=25)),
                ('valid', models.BooleanField(default=True)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='searcher.boat')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='users.saver')),
                ('saved_users', models.ManyToManyField(to='users.UserSaved')),
                ('savers', models.ManyToManyField(related_name='landed_missions', to='users.Saver')),
            ],
        ),
    ]
