# Generated by Django 3.1.13 on 2021-12-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211202_2204'),
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='saved_users',
            field=models.ManyToManyField(related_name='missions', to='users.UserSaved'),
        ),
    ]
