# Generated by Django 3.1.13 on 2021-12-03 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211203_0016'),
        ('searcher', '0002_auto_20211202_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='valid',
        ),
        migrations.AddField(
            model_name='mission',
            name='status',
            field=models.CharField(default='Pending', max_length=25, verbose_name=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')]),
        ),
        migrations.CreateModel(
            name='TechnicalReclamation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.saver')),
            ],
        ),
        migrations.CreateModel(
            name='MissionReclamation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searcher.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.saver')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_saved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersaved')),
            ],
        ),
    ]
